Audaxify1

diff --git a/contrib/make_tgz b/contrib/make_tgz
--- a/contrib/make_tgz
+++ b/contrib/make_tgz
@@ -5,7 +5,7 @@ set -e
 CONTRIB="$(dirname "$(readlink -e "$0")")"
 ROOT_FOLDER="$CONTRIB"/..
 PACKAGES="$ROOT_FOLDER"/packages/
-LOCALE="$ROOT_FOLDER"/electrum_mue/locale/
+LOCALE="$ROOT_FOLDER"/electrum_audax/locale/
 
 if [ ! -d "$LOCALE" ]; then
   echo "Run make_locale first!"
@@ -25,7 +25,7 @@ fi
     echo "<<<"
 
     # we could build the kivy atlas potentially?
-    #(cd electrum_mue/gui/kivy/; make theming) || echo "building kivy atlas failed! skipping."
+    #(cd electrum_audax/gui/kivy/; make theming) || echo "building kivy atlas failed! skipping."
 
     python3 setup.py --quiet sdist --format=zip,gztar
 )
diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -2,9 +2,9 @@
 
 # Parameterize
 PYTHON_VERSION=3.6.4
-BUILDDIR=/tmp/electrum-mue-build
-PACKAGE=Electrum-MUE
-GIT_REPO=https://github.com/muecoin/electrum-mue
+BUILDDIR=/tmp/electrum-audax-build
+PACKAGE=Electrum-AUDAX
+GIT_REPO=https://github.com/theaudaxproject/electrum-audax
 LIBSECP_VERSION="b408c6a8b287003d1ade5709e6f7bc3c7f1d5be7"
 
 . $(dirname "$0")/base.sh
@@ -71,7 +71,7 @@ git submodule update
 rm  -rf $BUILDDIR > /dev/null 2>&1
 mkdir $BUILDDIR
 
-cp -R ./contrib/deterministic-build/electrum-locale/locale/ ./electrum-mue/locale/
+cp -R ./contrib/deterministic-build/electrum-locale/locale/ ./electrum-audax/locale/
 
 
 info "Downloading libusb..."
@@ -124,18 +124,18 @@ done
 info "Building binary"
 APP_SIGN="$APP_SIGN" pyinstaller --noconfirm --ascii --clean --name $VERSION contrib/osx/osx.spec || fail "Could not build binary"
 
-info "Adding monetaryunit URI types to Info.plist"
+info "Adding audax URI types to Info.plist"
 plutil -insert 'CFBundleURLTypes' \
-	-xml '<array><dict> <key>CFBundleURLName</key> <string>monetaryunit</string> <key>CFBundleURLSchemes</key> <array><string>monetaryunit</string></array> </dict></array>' \
+	-xml '<array><dict> <key>CFBundleURLName</key> <string>audax</string> <key>CFBundleURLSchemes</key> <array><string>audax</string></array> </dict></array>' \
 	-- dist/$PACKAGE.app/Contents/Info.plist \
 	|| fail "Could not add keys to Info.plist. Make sure the program 'plutil' exists and is installed."
 
 DoCodeSignMaybe "app bundle" "dist/${PACKAGE}.app" "$APP_SIGN" # If APP_SIGN is empty will be a noop
 
 info "Creating .DMG"
-hdiutil create -fs HFS+ -volname $PACKAGE -srcfolder dist/$PACKAGE.app dist/electrum-mue-$VERSION.dmg || fail "Could not create .DMG"
+hdiutil create -fs HFS+ -volname $PACKAGE -srcfolder dist/$PACKAGE.app dist/electrum-audax-$VERSION.dmg || fail "Could not create .DMG"
 
-DoCodeSignMaybe ".DMG" "dist/electrum-mue-${VERSION}.dmg" "$APP_SIGN" # If APP_SIGN is empty will be a noop
+DoCodeSignMaybe ".DMG" "dist/electrum-audax-${VERSION}.dmg" "$APP_SIGN" # If APP_SIGN is empty will be a noop
 
 if [ -z "$APP_SIGN" ]; then
     warn "App was built successfully but was not code signed. Users may get security warnings from macOS."
